# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'faker'
Spy.create(name: "Jonnel Benjamin",attack: 10, defense: 10, health_points: 100)

Location.create(name: "WeWork DC", city_information: "Well over a third of D.C. residents work for the government, so it’s no surprise that people think of this as a “company town.” But more accurately, it’s a city that many businesses choose because of the proximity to the halls of power: advocacy groups, media outlets, and nonprofit organizations, to name a few. And lots of other industries, from healthcare to information technology, are seeing unprecedented growth. When looking for office space, companies here no longer need to lock themselves into a long-term lease. WeWork enables you to secure space with all the everyday amenities that spell success—dedicated front desk staff, spacious conference rooms, and impressive private offices—along with modern perks like month-to-month flexibility, passionate Community Managers, and special events. D.C.’s job growth is the highest in more than a decade, much of it fueled by a new wave of business. WeWork locations in the city and in northern Virginia help you make your own dream a reality.")
Location.create(name: "WeWork Berlin", city_information: "Berlin’s trajectory over the past two decades has leveraged its gritty roots to become one of the world’s most influential forces in art and culture. The arts and entertainment business is a sizeable sector of the Berlin economy, and professionals in these fields and many others find the room to do their best work at WeWork’s coworking spaces. Business leaders in tech, film, advertising, art, design, fashion and more are thriving here, and it’s easy to get in on the action at WeWork. Our community members enjoy more than just a beautifully designed workspace. WeWork’s amenities include all the small niceties that help free up mental space and drive productivity. You’ll enjoy endless fresh coffee, dedicated front desk service, and modern meeting rooms, but more unique perks as well like month-to-month flexibility, personalized help from Community Managers, access to a global network of entrepreneurs, special events, and more. As Berlin’s economy continues to reinvent itself, join a community that doesn’t just welcome change, but spurs it.")
Location.create(name: "WeWork San Francisco", city_information: "Since the ‘90s, San Francisco’s economy has evolved from tourism and trade to the growing fields of tech and finance. WeWork’s coworking spaces host some of the most innovative digital startups, powerful finance firms, and more. Although the Bay Area is bursting with young entrepreneurs, you’ll also work alongside some of the more established names in business too. Our locations provide the everyday perks that help make any business run smoothly, like endless hot coffee, dedicated front desk service, and modern meeting rooms. Our members enjoy also enjoy more unique benefits, like personal assistance from Community Managers, month-to-month flexibility, access to a global network, thoughtful events, and more. All our locations are close to transportation and tons of popular after-work hangouts, making WeWork the perfect place to base your team.")
Location.create(name: "WeWork Brussels", city_information: "For centuries, Brussels has hosted fairs featuring new ideas in art, music, and science. Today, the city’s influence extends well beyond its borders—and WeWork’s shared offices help businesses innovate and succeed. Amenities including high-speed internet, printing services, and friendly onsite staff take care of daily operations; perks like curated onsite events and an endless supply of micro-roasted coffee keep your team happy and engaged. With flexible agreements and beautiful, turnkey spaces, WeWork makes it easy to stay agile in Brussels. Schedule a visit today.")
Location.create(name: "WeWork Prague", city_information: "A frontrunner in the Czech economy, Prague is a prime location to grow your business, and WeWork’s shared office spaces put you right in the action—at the heart of the city’s commerce, technology, and media centers. Designed to inspire innovation and enhance productivity, WeWork’s spaces are suited for startups and big business alike. Free-flowing coffee keeps your team moving forward, while amenities such as fully stocked printing stations, front-desk service, and high-speed internet ensure daily operations run smoothly. Ready to elevate your business? Join WeWork’s coworking spaces in Prague today.")
Location.create(name: "WeWork Tokyo", city_information: "A world of contrasts, Tokyo is the fast-beating heart of Japan that fully embraces both time-honored tradition and tomorrow’s trends. As the world’s most populous metropolitan area with the highest number of Fortune 500 companies per capita, it only makes sense that WeWork would offer coworking space in this industrious mega-city. Entrepreneurs and enterprises alike thrive in this city’s ever-evolving and eclectic energy. With our flexible agreements and beautiful, turnkey spaces, WeWork’s Tokyo office locations are a winning solution for those looking to establish their business for a prosperous future.")
Location.create(name: "WeWork Jerusalem", city_information: "Steps away from Jerusalem’s Downtown Triangle business district, this shared office space puts your team in the center of the action. From private offices and shared desks to modern lounges and dedicated conference rooms, we built our two-floor King George location with productivity in mind. Here, teams from tech, law, and design enjoy an endless supply of micro-roasted coffee, a pet-friendly policy, and easy access to the bus and train via King George Street. Plus, nearby Machne Yehuda Market offers tons of tasty options for lunch, team outings, and client dinners. Why work anywhere else? WeWork King George has everything you need and then some. Schedule a tour today.")
Location.create(name: "WeWork Moscow", city_information: "Immersed in what’s increasingly becoming a global center of innovation, our coworking spaces in Moscow enable access to burgeoning industries with remarkable people eager to make a difference locally and abroad. Looking to find a home base for the future of your company? How about a temporary outpost for your satellite teams? Either way, at WeWork you’ll discover a premium entry point to the business communities of the RF.")
Location.create(name: "WeWork Madrid", city_information: "Marking WeWork’s introduction to the city of Madrid, our flexible office space on Castellana 43 puts you in the heart of the lively Chamberí neighborhood. Teams of every size and industry love this location’s seven floors of dedicated coworking space, complete with cozy lounges, sleek conference rooms, and private offices you can make your own. With four Metro stations within walking distance, commuting is simple no matter where you’re coming from. After work, admire the incredible architecture of Sorolla Museum, or head over to Plaza de Olavide for team drinks on an outdoor terrace. WeWork’s Paseo de la Castellana coworking space has it all—book a tour today to come see for yourself.")
Location.create(name: "WeWork Jakarta", city_information: "Once a popular tourist destination, Indonesia’s seaside capital has experienced a groundswell of growth and urban development in recent years. Whether you’re building your business from the ground up or already running an established enterprise, WeWork’s inspiring Jakarta coworking spaces provide the ideal environment for continued innovation—in Indonesia and beyond. With a rich culture and ample investment opportunities, there’s never been a better time to set up shop in Jakarta. Join WeWork today to reap the benefits.")
Location.create(name: "WeWork Lima", city_information: "Welcome to Lima, a vibrant seaside city just a hop, skip, and a jump away from the epic Andes mountains, and a flourishing place to grow your business. Recent years have transformed this locale into a burgeoning cultural hotspot, making it one of the Southern Hemisphere’s top destinations for food and art. Add to that a new era of startups mixed with economic foundation built on banking and natural resources, and you get a diverse business landscape that’s full of opportunity—especially when you’re part of WeWork’s global community.")

Mission.create(spy_id: 1, location_id: 1)

Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..15), defense: Faker::Number.within(1..15), health_points: Faker::Number.within(1..150), location_id: 1)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..15), defense: Faker::Number.within(1..15), health_points: Faker::Number.within(1..150), location_id: 2)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..15), defense: Faker::Number.within(1..15), health_points: Faker::Number.within(1..150), location_id: 3)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..15), defense: Faker::Number.within(1..15), health_points: Faker::Number.within(1..150), location_id: 4)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..15), defense: Faker::Number.within(1..15), health_points: Faker::Number.within(1..150), location_id: 5)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..15), defense: Faker::Number.within(1..15), health_points: Faker::Number.within(1..150), location_id: 6)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..15), defense: Faker::Number.within(1..15), health_points: Faker::Number.within(1..150), location_id: 7)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..15), defense: Faker::Number.within(1..15), health_points: Faker::Number.within(1..150), location_id: 8)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..15), defense: Faker::Number.within(1..15), health_points: Faker::Number.within(1..150), location_id: 9)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..15), defense: Faker::Number.within(1..15), health_points: Faker::Number.within(1..150), location_id: 10)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..15), defense: Faker::Number.within(1..15), health_points: Faker::Number.within(1..150), location_id: 11)
