# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'faker'
Spy.create(name: "Jonnel Benjamin",attack: 10, defense: 10, health_points: 50)

Location.create(name: "WeWork DC", city_information: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Location.create(name: "WeWork Berlin", city_information: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Location.create(name: "WeWork San Francisco", city_information: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Location.create(name: "WeWork Brussels", city_information: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Location.create(name: "WeWork Prague", city_information: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Location.create(name: "WeWork Tokyo", city_information: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Location.create(name: "WeWork Jerusalem", city_information: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Location.create(name: "WeWork Moscow", city_information: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Location.create(name: "WeWork Madrid", city_information: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Location.create(name: "WeWork Jakarta", city_information: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Location.create(name: "WeWork Lima", city_information: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")

Mission.create(spy_id: 1, location_id: 1)

Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..10), defense: Faker::Number.within(1..10), health_points: Faker::Number.within(1..100), location_id: 1)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..10), defense: Faker::Number.within(1..10), health_points: Faker::Number.within(1..100), location_id: 2)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..10), defense: Faker::Number.within(1..10), health_points: Faker::Number.within(1..100), location_id: 3)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..10), defense: Faker::Number.within(1..10), health_points: Faker::Number.within(1..100), location_id: 4)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..10), defense: Faker::Number.within(1..10), health_points: Faker::Number.within(1..100), location_id: 5)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..10), defense: Faker::Number.within(1..10), health_points: Faker::Number.within(1..100), location_id: 6)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..10), defense: Faker::Number.within(1..10), health_points: Faker::Number.within(1..100), location_id: 7)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..10), defense: Faker::Number.within(1..10), health_points: Faker::Number.within(1..100), location_id: 8)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..10), defense: Faker::Number.within(1..10), health_points: Faker::Number.within(1..100), location_id: 9)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..10), defense: Faker::Number.within(1..10), health_points: Faker::Number.within(1..100), location_id: 10)
Leader.create(name: Faker::Name.unique.name,attack: Faker::Number.within(1..10), defense: Faker::Number.within(1..10), health_points: Faker::Number.within(1..100), location_id: 11)
